# kzchat

Self-hosted Vim-style terminal chat built with Go.

## Features

- Terminal UI using [Bubble Tea](https://github.com/charmbracelet/bubbletea)
- Backend API with [Fiber](https://github.com/gofiber/fiber)
- Database queries generated by [SQLC](https://github.com/kyleconroy/sqlc)
- Database migrations via [golang-migrate](https://github.com/golang-migrate/migrate)
- JWT auth
- Real-time communication via WebSockets

## Requirements

- Go 1.20+
- PostgreSQL
- `migrate` CLI tool (for running migrations)

## Installation

Clone the repo:

```bash
git clone https://github.com/yourusername/kzchat.git
cd kzchat
```

Run the install script (will build client/server and configure `.env`):

```bash
./install.sh
```

Edit the config file at `/etc/kzchat/.env` if needed.

## Usage

Start the server:

```bash
kzchat-server
```

Run the terminal chat client:

```bash
kzchat
```

## Development

- Use `go build` to compile binaries in `./cmd/tui` and `./cmd/server`.
- Run migrations with:

```bash
migrate -path ./migrations -database "$DB_URL" up
```

## License

MIT License. See [LICENSE](LICENSE).